#!/bin/bash
# Simple Menu script which uses rofi
# Can be used search various websites
# To add a new website just follow the syntax

# Global Variables
DMENU="rofi -dmenu -i -l"
# Can be uncommented if a specific browser is prefered. Otherwise the default BROWSER environment varible will be used
#BROWSER=firefox


# Supported Websites
# Add new ones below (keep all websites below the line "declare -A website")
declare -A website
website[Google]="https://www.google.com/search?q="
website[Youtube]="https://www.youtube.com/results?search_query="
website[ArchWiki]="https://wiki.archlinux.org/index.php?search="
website[Nyaa]="https://nyaa.si/?f=0&c="
website[Animixplay]="https://animixplay.to/?q="
website[Anilist]="https://anilist.co/search/anime?search="
website[MyAnimeList]="https://myanimelist.net/search/all?q="
website[Wikipedia]="https://en.wikipedia.org/wiki/Special:Search?search="
website[Thesaurus]="https://www.thesaurus.com/browse/"


# Categories in Nyaa
nyaa_options(){
    declare -A categories
    categories["All Categories"]="0_0"
    categories["1. Anime"]="1_0"
    categories["1.1. Anime - Music Video"]="1_1"
    categories["1.2. Anime - English Translated"]="1_2"
    categories["1.3. Anime - Non-English Translated"]="1_3"
    categories["1.4. Anime - Raw"]="1_4"
    categories["2. Audio"]="2_0"
    categories["2.1. Audio - Lossless"]="2_1"
    categories["2.2. Audio - Lossy"]="2_2"
    categories["3. Literature"]="3_0"
    categories["3.1. Literature - English Translated"]="3_1"
    categories["3.2. Literature - Non-English Translated"]="3_2"
    categories["3.3. Literature - Raw"]="3_3"
    categories["4. Live Action"]="4_0"
    categories["4.1. Live Action - English Translated"]="4_1"
    categories["4.2. Live Action - Idol/Promotional Video"]="4_2"
    categories["4.3. Live Action - Non-English Translated"]="4_3"
    categories["4.4. Live Action - Raw"]="4_4"
    categories["5.0. Pictures"]="5_0"
    categories["5.1. Pictures - Graphics"]="5_1"
    categories["5.2. Pictures - Photos"]="5_2"
    categories["6. Software"]="6_0"
    categories["6.1. Software - Applications"]="6_1"
    categories["6.2. Software - Games"]="6_2"

    category="$(printf "%s\n" "${!categories[@]}" | sort -n | $DMENU 24 -p "Choose Nyaa Category:")"
    modifier="${categories["$category"]}"
    echo $modifier
}


# Shows information about this command
help() {
    echo "usage: search [-h]"
    echo ""
    echo "Opens a menu to search various websites"
    echo ""
    echo "options:"
    echo "  -h, --help  show this help message and exit"
}


main() {
    while [[ -z "${website[${site}]}" ]]; do
        site=$(printf "%s\n" "${!website[@]}" | sort | $DMENU 20 -p "Choose Search Engine:")
        # Ensures the pressing Esc quits the program
        [[ -z $site ]] && exit 1
    done
    
    url="${website["$site"]}"

    # Selecting Categories for Nyaa
    case $site in
        Nyaa) category=$(nyaa_options);;
    esac
    query=$(echo "" | $DMENU 20 -p "Search ${site}:" | jq -sRr @uri)
    
    # Searching the selected site and categories (if applicable)
    case $site in
        Nyaa) $BROWSER "${url}""${category}""&q=""${query}";;
        *) $BROWSER "${url}""${query}"
    esac
     
}


# Shows help if the options are used
if [[ $1 = '-h' ]] || [[ $1 = '--help' ]]; then
    help
    exit 0
else
    main
fi

